name: Release & Publish

on:
  push:
    branches:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      DOCKER_ORG_NAME: dbctestorg
      BUILD_CLOUD_BUILDER_NAME: demo

      HUB_USERNAME: damasohierro675
      HUB_REPOSITORY_NAME: dbc-flask-demo

      builder-type: cloud

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_ORG_NAME }}
          password: ${{ secrets.DOCKER_ORG_TOKEN }}


      - name: Set up Docker Buildx (cloud)
        if: env.builder-type == 'cloud'
        uses: docker/setup-buildx-action@v3
        with:
          version: lab:edge
          driver: cloud
          endpoint: ${{ env.DOCKER_ORG_NAME }}/${{ env.BUILD_CLOUD_BUILDER_NAME }}
          install: true

      - name: Set up Docker Buildx (local)
        if: env.builder-type == 'local'
        uses: docker/setup-buildx-action@v3
        with:
            install: true

      - name: Determine next major tag
        id: tag
        run: |
          git fetch --tags
          latest_major_tag=$(git tag --list 'v[0-9]*' | sort -Vr | head -n1)
          if [[ -z "$latest_major_tag" ]]; then
            next_tag="v1"
          else
            major=$(( ${latest_major_tag#v} + 1 ))
            next_tag="v$major"
          fi
          echo "Next tag: $next_tag"
          echo "tag=$next_tag" >> "$GITHUB_OUTPUT"

      - name: Create and push git tag
        run: |
          git tag ${{ steps.tag.outputs.tag }}
          git push origin ${{ steps.tag.outputs.tag }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.HUB_USERNAME }}/${{ env.HUB_REPOSITORY_NAME }}:${{ steps.tag.outputs.tag }}
